spring:
  datasource:
    url: jdbc:mysql://localhost:3308/rental_home
    username: user
    password: 123
  sql:
    init:
      mode: always

  jpa:
    generate-ddl: true
    defer-datasource-initialization: true
    show-sql: false
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 253360282070-rq32q8kdkguekjf3qbp859m799hm6pg2.apps.googleusercontent.com
            clientSecret: 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
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 100MB
      max-request-size: 100MB
  mail:
    host: smtp.gmail.com
    username: quantriviennhatro@gmail.com
    password: urnfgynzxjazyzlv
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
file:
  uploadDir: /hdd/data/photographer/upload/
  tempExportExcel: /hdd/data/photographer/tmp/
  libreOfficePath: /hdd/setup/libreoffice/opt/libreoffice6.4/program/
app:
  auth:
    tokenSecret: 04ca023b39512e46d0c2cf4b48d5aac61d34302994c87ed4eff225dcf3b0a218739f3897051a057f9b846a69ea2927a587044164b7bae5e1306219d50b588cb1
    tokenExpirationMsec: 864000000
  cors:
    allowedOrigins: http://localhost:3000,http://localhost:8080
  oauth2:
    authorizedRedirectUris:
      - http://localhost:3000/oauth2/redirect
      - http://localhost:8080/oauth2/callback/google
      - myandroidapp://oauth2/redirect
      - myiosapp://oauth2/redirect

